basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket-summary'),
    path('add/', views.basket_add, name='basket-add'),
    path('delete/', views.basket_delete, name='basket-delete'),
    path('update/', views.basket_update, name='basket-update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}ecommerce_store {% endblock %}</title>
    <!-- <link rel="stylesheet" href="{% static 'js/ailwind.js' %}" /> -->
    <script src="{% static 'js/tailwind.js' %}"></script>
  </head>
  <body>
    <!-- header -->
    {% include 'components/header.html' %}
    <!-- list category  -->
    <!-- {% include 'components/list_category.html' %} -->
    <!-- end header -->
    <!-- content -->
    <div class="content">{% block content %} {% endblock %}</div>
    <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->
    <!-- adding jquery  -->
    <script>
      const delete_url = "{% url 'basket:basket-delete' %}";
      const csrf_token = "{{csrf_token}}";
      const update_url = "{% url 'basket:basket-update' %}";
    </script>
    <script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>