basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket-summary'),
    path('add/', views.basket_add, name='basket-add'),
    path('delete/', views.basket_delete, name='basket-delete'),
    path('update/', views.basket_update, name='basket-update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

# app name
app_name = 'store'


# url path
urlpatterns = [
    path('', views.homepage, name='home'),
    path('categories/<slug:category_slug>', views.category_product, name='category-product'),
    path('products/<slug:slug>', views.product_detail, name='product-detail'),
]

store/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()

# category table and Product
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    
    
    class Meta:
        verbose_name_plural = 'categories'
        
    @property
    def get_absolute_url(self):
        return reverse('store:category-product', kwargs={'category_slug': self.slug})
    
    
    def __str__(self) -> str:
        return self.name

class ProductManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(in_stock = True, in_active= True)
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product')
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product_images/',
                              default='media/product_images/improving.jpg')
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=4,decimal_places=2)
    in_stock = models.BooleanField(default=True)
    in_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManger()
    
    class Meta:
        ordering = ('-created',)
    
    # view single page for product - return url 
    @property
    def get_view_url(self):
        return reverse('store:product-detail', kwargs={'slug': self.slug})
    
    
    # return str method
    def __str__(self) -> str:
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def homepage(request):
    '''
        homepage - render all product in html pages
    '''
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})




# single product
def product_detail(request, slug):
    '''
        product-detail -> for return single page for product to ordering 
    '''
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'store/product_detail.html', {'product': product})


def category_product(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.products.filter(category = category)
    return render(request, 'store/category_product.html', {'category': category, 'products': products})

templates/store/c_product.html
<!-- extends  -->
{% extends 'base.html' %}

<!-- content  -->
{% block content %}

<!--  Product Grid -->
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="mb-4 py-2 border-b border-gray-400">
      <h3 class="font-bold text-lg">Products For Category: {{category}}</h3>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for product in products %}
      <div class="p-4 md:w-1/3">
        <div
          class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden"
        >
          <img
            class="lg:h-48 md:h-36 w-full object-cover object-center"
            src="{{product.image.url}}"
            alt="blog"
          />
          <div class="p-6">
            <h2
              class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"
            >
              {{product.category.name}}
            </h2>
            <h1 class="title-font text-lg font-medium text-gray-900 mb-3">
              {{product.title|title}}
            </h1>
            <p class="leading-relaxed mb-3">
              {{product.description|slice:":150"}}
            </p>
            <div class="flex items-center flex-wrap">
              <a
                href="{{product.get_view_url}}"
                class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
                >View Detail
                <svg
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!--  end Product Grid -->
{% endblock %}

templates/store/category_product.html
<!-- extends  -->
{% extends 'base.html' %}

<!-- content  -->
{% block content %}

<!--  Product Grid -->
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="mb-4 py-2 border-b border-gray-400">
      <h3 class="font-bold text-lg">Products For Category: {{category}}</h3>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for product in products %}
      <div class="p-4 md:w-1/3">
        <div
          class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden"
        >
          <img
            class="lg:h-48 md:h-36 w-full object-cover object-center"
            src="{{product.image.url}}"
            alt="blog"
          />
          <div class="p-6">
            <h2
              class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"
            >
              {{product.category.name}}
            </h2>
            <h1 class="title-font text-lg font-medium text-gray-900 mb-3">
              {{product.title|title}}
            </h1>
            <p class="leading-relaxed mb-3">
              {{product.description|slice:":150"}}
            </p>
            <div class="flex items-center flex-wrap">
              <a
                href="{{product.get_view_url}}"
                class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0"
                >View Detail
                <svg
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  stroke-width="2"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!--  end Product Grid -->
{% endblock %}

templates/store/detail.html
{% extends 'base.html' %}

<!-- content -->
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="{{product.image.url}}"
      />
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">
          {{product.category.name}}
        </h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">
          {{product.title|title}}
        </h1>
        <div class="flex mb-4"></div>
        <p class="leading-relaxed mt-4">{{product.description|slice:":255"}}</p>
        <div
          class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5"
        >
          <div class="flex ml-6 items-center">
            <span class="mr-3">Order Product</span>
            <div class="relative">
              <input
                type="number"
                name=""
                id=""
                class="border border-gray-500 py-1 px-2 rounded"
                max="10"
                min="0"
                value="1"
              />
            </div>
          </div>
        </div>

        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"
            >${{product.price}}</span
          >
          <a
            class="flex ml-auto text-white bg-indigo-500 border-0 py-1 px-8 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Buy
          </a>
          <!-- <a
            class="flex ml-4 text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Order
          </a> -->
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/store/home.html
<!-- extends  -->
{% extends 'base.html' %}

<!-- content  -->
{% block content %}
<!-- Hero Section -->
{% include 'components/store/hero.html' %}
<!-- end hero -->
<!--  Product Grid -->
{% include 'components/store/product.html' %}
<!--  end Product Grid -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}

<!-- content -->
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="{{product.image.url}}"
      />
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">
          {{product.category.name}}
        </h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">
          {{product.title|title}}
        </h1>
        <div class="flex mb-4"></div>
        <p class="leading-relaxed mt-4">{{product.description|slice:":255"}}</p>
        <div
          class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5"
        >
          <div class="flex ml-6 items-center">
            <span class="mr-3">Order Product</span>
            <div class="relative">
              <input
                type="number"
                name="items_count"
                id="product_count"
                class="border border-gray-500 py-1 px-2 rounded"
                max="10"
                min="0"
                value="1"
              />
            </div>
          </div>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900"
            >${{product.price}}</span
          >
          <button
            id="add-button"
            value="{{product.id}}"
            class="flex ml-auto text-white bg-indigo-500 border-0 py-1 px-8 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Buy
          </button>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  let add_button = document.getElementById("add-button");
  add_button.addEventListener("click", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'basket:basket-add' %}",
      data: {
        product_id: add_button.value,
        product_qty: document.getElementById("product_count").value,
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },

      success: function (json) {
        // get data to send to basket
        document.getElementById("basket_qty").innerHTML = json.qty;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>
{% endblock %}