account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .forms import (UserLoginForm, PWRestConfirmForm, PWRestForm)
from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate_user, name='activate'),
    path('dashboard/',views.user_dashboard, name='dashboard'),
    
    # auth views
    path('login/', auth_views.LoginView.as_view(
        template_name = 'account/login.html',
        form_class = UserLoginForm,
        
    ), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/account/login/'), name = 'logout'),
    path('edit/', views.profile_edit, name = 'profile-edit'),
    path('delete_user/', views.delete_user, name='delete-user'),
    path('delete-confirm/', TemplateView.as_view(
        template_name= 'account/user/delete_confirm.html'
        ), name='delete-confirmation'),
    path('password-rest/', auth_views.PasswordResetView.as_view(
        template_name = 'account/user/password_reset_form.html',
        success_url = 'password-reset-email-confirm',
        email_template_name = 'account/components/password_reset_email.html',
        form_class = PWRestForm
        ), name='pwdreset'),
    
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name = 'account/user/password_reset_confirm.html',
             success_url = '/account/password-reset-complete/',
             form_class = PWRestConfirmForm
             ),
         name='password_reset_confirm'),
    path('password-rest/password-reset-email-confirm/', TemplateView.as_view(
        template_name = 'account/user/reset_status.html'
    ), name = 'password_reset_done'),
    path('password-reset-complete/', 
         TemplateView.as_view(
             template_name = 'account/user/reset_status.html'
        ),  name = 'password_reset_complete')
    
    
]

basket/urls.py
from django.urls import path
from . import views


app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket-summary'),
    path('add/', views.basket_add, name='basket-add'),
    path('delete/', views.basket_delete, name='basket-delete'),
    path('update/', views.basket_update, name='basket-update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/header.html
<nav class="bg-white border-gray-200 border-b border-1 px-2 sm:px-4 py-2.5">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a href="/" class="flex items-center">
      <!-- <img
        src="https://flowbite.com/docs/images/logo.svg"
        class="h-6 mr-3 sm:h-9"
        alt="Flowbite Logo"
      /> -->
      <span class="self-center text-xl font-semibold whitespace-nowrap"
        >Shopping Store</span
      >
    </a>
    <div class="flex md:order-2">
      <button
        type="button"
        data-collapse-toggle="navbar-search"
        aria-controls="navbar-search"
        aria-expanded="false"
        class="md:hidden text-gray-500 hover:bg-gray-100 -700 focus:outline-none focus:ring-4 focus:ring-gray-200 rounded-lg text-sm p-2.5 mr-1"
      >
        <svg
          class="w-5 h-5"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <span class="sr-only">Search</span>
      </button>
      <div class="relative hidden md:block">
        <div
          class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none"
        >
          <svg
            class="w-5 h-5 text-gray-500"
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <span class="sr-only">Search icon</span>
        </div>
        <input
          type="text"
          id="search-navbar"
          class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500"
          placeholder="Search..."
        />
      </div>
      <button
        data-collapse-toggle="navbar-search"
        type="button"
        class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
        aria-controls="navbar-search"
        aria-expanded="false"
      >
        <span class="sr-only">Open menu</span>
        <svg
          class="w-6 h-6"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>

    <a
      href="{% url 'basket:basket-summary' %}"
      class="flex md:order-2 bg-blue-500 py-2 px-2 rounded text-white"
    >
      <div id="count_item_in_cart" class="flex">
        <span id="basket_qty" class="mr-3">
          {% with total_qty=basket|length %}
          <!-- if total _qty more than 0 -->
          {% if total_qty > 0 %} {{total_qty}} {% else %} 0 {% endif %}
          <!-- end with  -->
          {% endwith %}
        </span>

        <svg
          class="w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.5"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
          aria-hidden="true"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
          ></path>
        </svg>
      </div>
      <button type="button" class="font-semibold text-base mx-1">Cart</button>
    </a>
    <ul
      class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white"
    >
      {% if request.user.is_authenticated %}
      <li>
        <a
          href="{% url 'account:logout' %}"
          class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0"
          aria-current="page"
          >logout</a
        >
      </li>
      {% else %}
      <li>
        <a
          href="{% url 'account:login' %}"
          class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0"
          >Login</a
        >
      </li>
      <li>
        <a
          href="{% url 'account:register' %}"
          class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0"
          >register
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/components/list_category.html
<ul
  class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 py-3 text-gray-900 border-b border-1"
>
  {% for c in categories %}
  <li class="flex mx-auto p-2 md:p-0">
    {% if c == category%}
    <a
      href="{{c.get_absolute_url}}"
      class="flex justify-content-center mr-4 hover:underline md:mr-6 text-blue-700 font-bold"
      >{{c.name|title}}</a
    >
    {% else %}
    <a
      href="{{c.get_absolute_url}}"
      class="flex justify-content-center mr-4 hover:underline md:mr-6"
      >{{c.name|title}}</a
    >
    {% endif %}
  </li>
  {% endfor %}
</ul>